project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

from quality_control import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality/', include('quality_control.urls'))
]

project_tracker/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', views.projects_list, name='projects_list'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('projects/new/', views.create_project, name='create_project'),
    path('projects/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project')
    # path('another/', views.another_page, name='another_page')
]

project_tracker/tasks/models.py
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name


class Task(models.Model):
    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена'),
    ]
    project = models.ForeignKey(
        Project,
        related_name='tasks',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    assignee = models.ForeignKey(
        User,
        related_name='tasks',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='Now',
    )

project_tracker/tasks/forms.py
from django.forms import ModelForm
from .models import Project, Task

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description']


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'assignee']

project_tracker/tasks/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect, render

from tasks.forms import ProjectForm, TaskForm
from tasks.models import Project, Task

def index(request):
    return render(request, 'tasks/index.html')

def projects_list(request):
    projects = Project.objects.all()
    return render(request, 'tasks/projects_list.html', {'projects_list': projects})

def project_detail(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    return render(request, 'tasks/project_detail.html', {'project': project})

def task_detail(request, task_id, project_id):
    task = get_object_or_404(Task, id=task_id, project_id=project_id)
    return render(request, 'tasks/task_detail.html', {'task': task})

def another_page(request):
    return HttpResponse('Это другая страница приложения tasks')

def create_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:projects_list')
    else:
        form = ProjectForm()
    return render(request, 'tasks/project_create.html', {'form': form})

def add_task_to_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.project = project
            task.save()
            return redirect('tasks:task_list')
    else:
        form = TaskForm()
    return render(request, 'tasks/add_task.html', {'form': form, 'project': project})

project_tracker/tasks/templates/tasks/add_task.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Добавить задачу в проект {{ project.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать задачу</button>
    </form>
{% endblock %}

project_tracker/tasks/templates/tasks/index.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Страница приложения tasks</h1>
    <a href="{% url 'tasks:projects_list' %}">Список проектов</a>
{% endblock %}

project_tracker/tasks/templates/tasks/project_create.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Создать новый проект</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/tasks/templates/tasks/project_detail.html
{% extends 'base/base.html' %}

{% block content %}
<h1>{{ project.name }}</h1>
<p>{{ project.description }}</p>

<h2>Задачи в проекте</h2>

<p><a href="{% url 'tasks:add_task_to_project' project.id %}">Добавить новую задачу</a></p>

<ul>
    {% for task in project.tasks.all %}
        <li><a href="{% url 'tasks:task_detail' project.id task.id %}">{{ task.name }}</a> - {{ task.status }}</li>
    {% empty %}
        <li>В этом проекте пока нет задач.</li>
    {% endfor %}
</ul>
{% endblock %}

project_tracker/tasks/templates/tasks/projects_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Список проектов</h1>
<p><a href="{% url 'tasks:create_project' %}">Создать новый проект</a></p>
<ul>
    {% for project in projects_list %}
        <li><a href="{% url 'tasks:project_detail' project.id %}">{{ project.name }}</a></li>
    {% empty %}
        <li>Нет проектов</li>
    {% endfor %}
</ul>
{% endblock %}

project_tracker/tasks/templates/tasks/task_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>{{ task.name }}</h1>
    <p>{{ task.description }}</p>

    <ul>
        <li>Статус - {{ task.status }}</li>
        <li>Ответственный - {{ task.assignee }}</li>
    </ul>
{% endblock %}