project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

from quality_control import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality/', include('quality_control.urls'))
]

project_tracker/quality_control/urls.py
from django.contrib import admin
from django.urls import path, include

from quality_control import views

app_name='quality_control'

urlpatterns = [
    path('', views.index, name='index'),
    path('bugs/', views.bug_list, name='bugs'),
    path('bugs/<int:bug_id>/', views.BugDetailView.as_view(), name='bug_detail'),
    path('features/', views.feature_list, name='features'),
    path('features/<int:feature_id>/', views.FeatureDetailView.as_view(), name='feature_detail')
]

project_tracker/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', views.projects_list, name='projects_list'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('projects/new/', views.create_project, name='create_project'),
    path('projects/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project')
    # path('another/', views.another_page, name='another_page')
]

project_tracker/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <h1>Проект project-tracker</h1>
    </header>

    <nav>
        <a href="{% url 'tasks:index' %}">Приложение tasks</a>
        <a href="{% url 'quality_control:index' %}">Приложение quality_control</a>
    </nav>

    <main>
        {% block content %}

        {% endblock %}
    </main>

    <footer>
        
    </footer>
    
</body>
</html>