project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

from quality_control import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality/', include('quality_control.urls'))
]

project_tracker/quality_control/urls.py
from django.contrib import admin
from django.urls import path, include

from quality_control import views

app_name='quality_control'

urlpatterns = [
    path('', views.index, name='index'),
    path('bugs/', views.bug_list, name='bugs'),
    path('bugs/<int:bug_id>/', views.BugDetailView.as_view(), name='bug_detail'),
    path('features/', views.feature_list, name='features'),
    path('features/<int:feature_id>/', views.FeatureDetailView.as_view(), name='feature_detail')
]

project_tracker/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', views.projects_list, name='projects_list'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('projects/new/', views.create_project, name='create_project'),
    path('projects/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project')
    # path('another/', views.another_page, name='another_page')
]

project_tracker/quality_control/models.py
from django.db import models

from tasks.models import Project, Task

PRIORITY_CHOICES = [
        (5, 'Наивысший'),
        (4, 'Высокий'),
        (3, 'Обычный'),
        (2, 'Ниже среднего'),
        (1, 'Несущественный'),
    ]

class BugReport(models.Model):
    BUG_CHOICES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена'),
    ]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        related_name='bug_report_project',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    task = models.ForeignKey(
        Task,
        related_name='bug_report_tasks',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=BUG_CHOICES,
        default='New',
    )
    priority = models.IntegerField(
        choices=PRIORITY_CHOICES,
        default=0,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeatureRequest(models.Model):
    FEATURE_CHOICES = [
        ('Review', 'Рассмотрение'),
        ('Accepted', 'Принято'),
        ('Rejected', 'Отклонено'),
    ]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        related_name='feature_request_project',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    task = models.ForeignKey(
        Task,
        related_name='feature_request_task',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=FEATURE_CHOICES,
        default='Now',
    )
    priority = models.IntegerField(
        choices=PRIORITY_CHOICES,
        default=0,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

project_tracker/quality_control/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.detail import DetailView
from quality_control.models import BugReport, FeatureRequest

def index(request):
    return render(request, 'quality_control/index.html')

# def bug_list(request):
#     bugs = BugReport.objects.all()
#     bug_reports_html = "<h1>Cписок отчетов об ошибках</h1><ul>"
#     for report in bugs:
#         bug_reports_html += f'<li><a href="{report.id}/">{report.title} - статус "{report.status}"</a></li>'
#     bug_reports_html += '</ul>'
#     return HttpResponse(bug_reports_html)

def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bug_list.html', {'bugs_list': bugs})

# class BugDetailView(DetailView):
#     model = BugReport
#     pk_url_kwarg = 'bug_id'
    
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         bug = self.object
#         task = bug.task
#         project = bug.project
#         response_html = f"""<h1>Детали бага {bug.title} ({bug.id})</h1>
#             <p>
#                 Описание: {bug.description}
#             </p>
#             <ul>
#                 <li>Статус: {bug.status}</li>
#                 <li>Приоритет: {bug.priority}</li>
#                 <li>Проект: {project.name}</li>
#                 <li>Задача: {task.name}</li>
#             </ul>"""
#         return HttpResponse(response_html)

class BugDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_detail.html'

def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'features_list': features})
    # feature_requests_html = "<h1>Cписок запросов на улучшение</h1><ul>"
    # for feature_request in features:
    #     feature_requests_html += f'<li><a href="{feature_request.id}/">{feature_request.title} - статус "{feature_request.status}"</a></li>'
    # feature_requests_html += '</ul>'
    # return HttpResponse(feature_requests_html)

class FeatureDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    template_name = 'quality_control/feature_detail.html'
    # def get(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     feature = self.object
    #     task = feature.task
    #     project = feature.project
    #     response_html = f"""<h1>Детали запроса на улучшение {feature.title} ({feature.id})</h1>
    #         <p>
    #             Описание: {feature.description}
    #         </p>
    #         <ul>
    #             <li>Статус: {feature.status}</li>
    #             <li>Приоритет: {feature.priority}</li>
    #             <li>Проект: {project.name}</li>
    #             <li>Задача: {task.name}</li>
    #         </ul>"""
    #     return HttpResponse(response_html)

project_tracker/quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}
<h1>{{ bugreport.title }}</h1>
<p>Описание: {{ bugreport.description }}</p>

<h2>Задачи в проекте</h2>
<ul>
    <li>Статус: {{ bugreport.status }}</li>
    <li>Приоритет: {{ bugreport.priority }}</li>
    <li>Проект: {{ bugreport.project.name }}</li>
    <li>Задача: {{ bugreport.task.name }}</li>
</ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Cписок отчетов об ошибках</h1>
<ul>
    {% for bug in bugs_list %}
        <li><a href="{% url 'quality_control:bug_detail' bug.id %}">{{ bug.title }} - статус "{{ bug.status }}"</a></li>
    {% empty %}
        <li>Нет отчетов об ошибках</li>
    {% endfor %}
</ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
<h1>{{ featurerequest.title }}</h1>
<p>Описание: {{ featurerequest.description }}</p>

<h2>Детали запроса на улучшение</h2>
<ul>
    <li>Статус: {{ featurerequest.status }}</li>
    <li>Приоритет: {{ featurerequest.priority }}</li>
    <li>Проект: {{ featurerequest.project.name }}</li>
    <li>Задача: {{ featurerequest.task.name }}</li>
</ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Cписок запросов на улучшение</h1>
<ul>
    {% for feature in features_list %}
        <li><a href="{% url 'quality_control:feature_detail' feature.id %}">{{ feature.title }} - статус "{{ feature.status }}"</a></li>
    {% empty %}
        <li>Нет запросов на улучшение</li>
    {% endfor %}
</ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Система контроля качества</h1>
    <div>
        <a href="{% url 'quality_control:bugs' %}">Список всех багов</a>
        <a href="{% url 'quality_control:features' %}">Запросы на улучшение</a>
    </div>
{% endblock %}